apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    tier: front-end

spec:
  template:
     metadata:
        name: result-pod
        labels:
          app: result-app
          tier: front-end
     spec:
       containers:
        - name: result-ctr
          image: dountless/webapp:result
          ports:
           - containerPort: 80

  replicas: 4
  selector:
    matchLabels:
       app: result-app
    
