apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    tier: back-end

spec:
  template:
     metadata:
        name: worker-pod
        labels:
          app: worker-app
          tier: back-end
     spec:
       containers:
        - name: worker-ctr
          image: dountless/webapp:worker

  replicas: 2
  selector:
    matchLabels:
       app: worker-app
    
