apiVersion: apps/v1
kind: Deployment
metadata:
   name: flask-app-deploy
   labels:
     tier: front-end
spec:
   template:
      metadata:
        name: flask-app-pod
        labels:
          app: flask-app
          tier: front-end
      spec:
        containers:
         - name: flas-app-ctr
           image: dountless/webapp:flask_ubuntu
           ports:
             - containerPort: 5000
   replicas: 4
   selector:
      matchLabels:
         app: flask-app




