apiVersion: v1
kind: Service
metadata:
   name: flask-service
   labels:
     name: flask-service
     tier: front-end
spec:
   type: NodePort
   ports:
     - targetPort: 5000
       port: 5000
       nodePort: 30044
   selector:
         app: flask-app
         tier: front-end
  
