apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
     app: redis-service
     tier: back-end
spec:  
  ports:
    - targetPort: 6379
      port: 6379
  
  selector:
         app: redis-db
         tier: back-end

