apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    tier: back-end
    app: postgres-db

spec:
  containers:
  - name: postgres-ctr
    image: postgres
    ports:
     - containerPort: 5432
    env:
     - name: POSTGRES_USER
       value: "postgres"
     - name: POSTGRES_PASSWORD
       value: "postgres"



