apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    tier: back-end
    app: redis-db

spec:
   containers:
    - name: redis-ctr
      image: redis
      ports:
       - containerPort: 6379


