apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    tier: front-end
    app: voting-app

spec:
  containers:
  - name: voting-ctr
    image: dountless/webapp:voting
    ports:
      - containerPort: 80

