apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
     name: postgres-service
     tier: front-end
spec:
   ports:
    - targetPort: 5432
      port: 5432
   selector:
    tier: back-end
    app: postgres-db


