apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
     app: redis-db
     tier: front-end
spec:
  ports:
   - targetPort: 6379
     port: 6379
     
  selector:
    tier: back-end
    app: redis-db

