apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
     app: redis-db
     tier: back-end
spec:
  ports:
   - targetPort: 6379
     port: 6379
     
  selector:
        app: redis-app
        tier: back-end



