apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:  
    name: result-service
    tier: front-end
spec:
  type: NodePort
  ports:
   - targetPort: 80 
     port: 80
     nodePort: 30005
  selector:
        app: result-app
        tier: front-end




