apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment3
  labels:
     tier: nginx1

spec:
  template:
     metadata:
         name: myapp-pod
         labels:
            tier: nginx1
     spec:
        containers:
        - name: nginx1-ctr
          image: nginx:1.18

  replicas: 2 
  selector:
     matchLabels:
         tier: nginx1



