apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp 
    tier: front-end

spec:
  template:
    metadata:
       name: myapp-pod
       labels:
         tier: front-end
    spec:
       containers:
        - name: nginx-ctr
          image: nginx

  replicas: 6
  selector:
    matchLabels:
       tier: front-end


       
